library(BiocManager)
options(repos = BiocManager::repositories())
install.packages("BiocGenerics")
install.packages("GenomeInfoDbData")
install.packages("zlibbioc")
install.packages("Biobase")
install.packages("S4Vectors")
install.packages("annotationTools")
install.packages("IRanges")
install.packages("GenomeInfoDb")
install.packages("XVector")
install.packages("Biostrings")
install.packages("KEGGREST")
install.packages("AnnotationDbi")
install.packages("org.Ce.eg.db")
install.packages("org.Dm.eg.db")
install.packages("org.Dr.eg.db")
install.packages("org.Hs.eg.db")
install.packages("org.Mm.eg.db")
install.packages("org.Rn.eg.db")
install.packages("BiocFileCache")
install.packages("biomaRt")

install.packages("rsconnect")
require(remotes)
install_version("rsconnect", version = "0.8.16", repos = "http://cran.us.r-project.org")#choose 3
options(rsconnect.http = "curl")
options(rsconnect.max.bundle.size = 4145728000)
options(rsconnect.http = "curl")
